receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
    logLevel: info
  jaeger:
    endpoint: "http://jaeger:14268/api/traces"
    # Use the thrift over HTTP endpoint provided by Jaeger all-in-one

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [jaeger, logging]
    metrics:
      receivers: [otlp]
      exporters: [logging]

extensions:
  health_check: {}

telemetry:
  logs:
    level: info
